src/Kelpie.Web/Controllers/AppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Caching;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using Kelpie.Core;
using Kelpie.Core.Domain;
using Kelpie.Core.Repository;
using Kelpie.Web.Models;
using MongoDB.Driver;
using Environment = Kelpie.Core.Domain.Environment;

namespace Kelpie.Web.Controllers
{
    public class AppController : Controller
    {
        private readonly LogEntryRepository _repository;
        private readonly IConfiguration _configuration;

        public AppController()
        {
            _configuration = Configuration.Read();
            _repository = new LogEntryRepository(new MongoClient(), _configuration);
        }

        private Environment GetSelectedEnvironment()
        {
            string environmentName = Request.QueryString["environmentName"];

            if (string.IsNullOrEmpty(environmentName))
                environmentName = Request.Cookies["environmentName"]?.Value;

            Environment selectedEnvironment = null;
            if (!string.IsNullOrEmpty(environmentName))
                selectedEnvironment = _configuration.Environments.First(x => x.Name.Equals(environmentName, StringComparison.InvariantCultureIgnoreCase));

            if (selectedEnvironment == null)
                selectedEnvironment = _configuration.Environments.First();

            return selectedEnvironment;
        }

        public ActionResult Today(string applicationName)
        {
            Environment currentEnvironment = GetSelectedEnvironment();

            ViewBag.EnvironmentName = currentEnvironment.Name;
            ViewBag.ApplicationName = applicationName;

            var entries = _repository.GetEntriesToday(currentEnvironment.Name, applicationName);
            return View(entries);
        }

        public ActionResult ThisWeek(string applicationName)
        {
            Environment currentEnvironment = GetSelectedEnvironment();

            ViewBag.EnvironmentName = currentEnvironment.Name;
            ViewBag.ApplicationName = applicationName;

            var entries = _repository.GetEntriesThisWeek(currentEnvironment.Name, applicationName);
            return View(entries);
        }

        public ActionResult AllExceptionTypes(string applicationName)
        {
            Environment currentEnvironment = GetSelectedEnvironment();

            ViewBag.EnvironmentName = currentEnvironment.Name;
            ViewBag.ApplicationName = applicationName;

            var entries = _repository.GetEntriesThisWeekGroupedByException(currentEnvironment.Name, applicationName);
            return View(entries);
        }

        public ActionResult ExceptionType(string applicationName, string exceptionType)
        {
            Environment currentEnvironment = GetSelectedEnvironment();

            ViewBag.EnvironmentName = currentEnvironment.Name;
            ViewBag.ApplicationName = applicationName;
            ViewBag.ExceptionType = exceptionType;

            var entries = _repository.FindByExceptionType(currentEnvironment.Name, applicationName, exceptionType);
            return View(entries);
        }

        public ActionResult LoadMessage(Guid id)
        {
            LogEntry entry = _repository.GetEntry(id);
            return Content(HttpUtility.HtmlEncode(entry.Message.Trim()));
        }

		public ActionResult Search(string applicationName, string q)
        {
			Environment currentEnvironment = GetSelectedEnvironment();

			ViewBag.EnvironmentName = currentEnvironment.Name;
			ViewBag.ApplicationName = applicationName;
			ViewBag.SearchQuery = q;

			IEnumerable<LogEntry> results = new LogEntry[0];

			if (_configuration.IsLuceneEnabled)
			{
				var searchRepository = new SearchRepository(_configuration);
				string query = searchRepository.CreateLuceneSearchSyntax(applicationName, currentEnvironment.Name, q);
				results = searchRepository.Search(query);
			}
			else
			{
				// Use MongoDB's slower search.
				results = _repository.Search(currentEnvironment.Name, applicationName, q);
			}

			return View(results);
        }
    }
}

src/Kelpie.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Caching;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using Kelpie.Core;
using Kelpie.Core.Domain;
using Kelpie.Core.Repository;
using Kelpie.Web.Models;
using MongoDB.Driver;
using Environment = Kelpie.Core.Domain.Environment;

namespace Kelpie.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly LogEntryRepository _repository;
        private readonly IConfiguration _configuration;

        public HomeController()
        {
            _configuration = Configuration.Read();
            _repository = new LogEntryRepository(new MongoClient(), _configuration);
        }

        public ActionResult Index()
        {
            Environment selectedEnvironment = GetSelectedEnvironment();
            Response.Cookies.Add(new HttpCookie("environmentName", selectedEnvironment.Name));

            var homepageModel = new HomepageViewModel();
            homepageModel.Environments = _configuration.Environments.Select(x => x.Name);
            homepageModel.CurrentEnvironment = selectedEnvironment.Name;

            string cacheKey = GetCacheKey();

            if (MemoryCache.Default.Contains(cacheKey))
            {
                List<ServerViewModel> list = MemoryCache.Default.Get(cacheKey) as List<ServerViewModel>;
                homepageModel.ServerModels = list;

                return View(homepageModel);
            }
            else
            {
                HostingEnvironment.QueueBackgroundWorkItem((token) =>
                {
                    List<ServerViewModel> list = GetDashboardData(selectedEnvironment);
                    homepageModel.ServerModels = list;
                    MemoryCache.Default.Add(cacheKey, list, DateTimeOffset.MaxValue);
                });

                return View("CrunchingData", homepageModel);
            }
        }

        private string GetCacheKey()
        {
            return string.Format("kelpie.dashboard.{0}", GetSelectedEnvironment().Name);
        }

        private Environment GetSelectedEnvironment()
        {
            string environmentName = Request.QueryString["environmentName"];

            if (string.IsNullOrEmpty(environmentName))
                environmentName = Request.Cookies["environmentName"]?.Value;

            Environment selectedEnvironment = null;
            if (!string.IsNullOrEmpty(environmentName))
                selectedEnvironment = _configuration.Environments.First(x => x.Name.Equals(environmentName, StringComparison.InvariantCultureIgnoreCase));

            if (selectedEnvironment == null)
                selectedEnvironment = _configuration.Environments.First();

            return selectedEnvironment;
        }

        private List<ServerViewModel> GetDashboardData(Environment environment)
        {
            var list = new List<ServerViewModel>();

            foreach (string applicationName in _configuration.Applications.OrderBy(x => x))
            {
                List<LogEntry> entries = _repository.GetEntriesSince(environment.Name, applicationName, _configuration.MaxAgeDays).ToList();
                var topException = entries.GroupBy(x => x.ExceptionType)
                    .OrderByDescending(x => x.Count());

                string exceptionType = "";
                var topItem = topException.FirstOrDefault();
                if (topItem != null)
                    exceptionType = topItem.Key;

                var model = new ServerViewModel()
                {
                    Application = applicationName,
                    TopExceptionType = exceptionType,
                    ErrorCount = entries.Count,
                    ErrorCountPerServer = entries.Count / environment.Servers.Count(),
                    ServerCount = environment.Servers.Count()
                };

                list.Add(model);
            }

            return list;
        }

        public ActionResult GetCacheDataStatus()
        {
            string cacheKey = GetCacheKey();
            bool hasData = MemoryCache.Default.Get(cacheKey) != null;
            return Json(hasData, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ClearCache()
        {
            foreach (KeyValuePair<string, object> keyValuePair in MemoryCache.Default)
            {
                if (keyValuePair.Key.StartsWith("kelpie."))
                    MemoryCache.Default.Remove(keyValuePair.Key);
            }

            return Content("All cache keys for Kelpie cleared.");
        }
    }
}

src/Kelpie.Web/Views/Home/CrunchingData.cshtml
@model HomepageViewModel
@{
	ViewBag.Title = "Preloading dashboard data.";
}

<div class="row">
	<h3>Crunching log file data</h3>
	<p>
		This may take a few minutes.
	</p>

	<div class="progress">
		<div class="indeterminate"></div>
	</div>
</div>

@section scripts
{
	<script type="text/javascript">

		var intervalHandle;

		$(document).ready(function () {
			intervalHandle = setInterval("getStatus()", 1000);
		});

		function getStatus() {
			$.ajax({
					method: "GET",
					url: "/Home/GetCacheDataStatus",
				})
				.done(function (data) {
					console.log("GetCacheDataStatus: " + data);
					if (data === true) {
						intervalHandle = null;
						window.location.href = "/";
					}
				});
		}
	</script>
}

src/Kelpie.Web/Views/Home/Index.cshtml
@model HomepageViewModel
@{
	ViewBag.Title = "Welcome the Kelpie app.";
}

@section AdditionalNav
{
	<li>
		<a class="dropdown-button" href="#!" data-activates="dropdown1">Environment<i class="material-icons right">arrow_drop_down</i></a>
	</li>

	<!-- Environments -->
	<ul id="dropdown1" class="dropdown-content">
		@foreach (string environment in Model.Environments)
		{
			<li>
				<a href="@Url.Action("Index", "Home", new {environmentName = environment})">@environment</a>
			</li>
		}
	</ul>
}

<div class="row">
	<h3>@Model.CurrentEnvironment</h3>

	<div class="row" id="dashboard">
		@foreach (ServerViewModel item in Model.ServerModels)
			{
			<div class="col s3">
				<div class="card blue-grey">
					<div class="card-content white-text">
						<span class="card-title"><a href="@Url.Action("Today", "App", new { applicationName = item.Application})">@item.Application</a></span>
						<div class="new badge">@item.ErrorCount errors this week on @item.ServerCount servers.</div>
						<div class="new badge">With an average of @item.ErrorCountPerServer per server.</div>
						<div class="top-exception">

							@if (!string.IsNullOrWhiteSpace(item.TopExceptionType))
							{
								<span class="label teal darken-4">Top exception:</span><br />
								<div class="exception-type"><a href="@Url.Action("ExceptionType", "App", new {applicationName = item.Application, exceptionType = item.TopExceptionType})">@item.TopExceptionType</a></div>
							}
						</div>
					</div>
					<div class="card-action">
						<ul>
							<li><a href="@Url.Action("ThisWeek", "App", new {applicationName = item.Application})">View this week's logs</a></li>
							<li><a href="@Url.Action("AllExceptionTypes", "App", new { applicationName = item.Application})">View top exceptions</a></li>
						</ul>
					</div>
				</div>
			</div>
			}
	</div>
</div>